### ISSUE TITLE
请问这个错误是什么原因造成的？

### ISSUE THREAD

**Issue by rebelboy** [v3ucn/Bert-VITS2-Extra_-#3]
在使用 Bert-VITS2-Extra 中文特化版的时候，底模使用的是网上下载的 [Bert-VITS2_中文特化修复底]

Active code page: 65001
首次训练开始
加载config中的配置localhost
加载config中的配置10086
加载config中的配置1
加载config中的配置0
加载config中的配置0
加载环境变量
MASTER_ADDR: localhost,
MASTER_PORT: 10086,
WORLD_SIZE: 1,
RANK: 0,
LOCAL_RANK: 0
Data/WangMingJun
03-27 10:41:45 INFO     | data_utils.py:65 | Init dataset...
100%|██████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<?, ?it/s]
03-27 10:41:45 INFO     | data_utils.py:80 | skipped: 0, total: 17
03-27 10:41:45 INFO     | data_utils.py:65 | Init dataset...
100%|████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]
03-27 10:41:45 INFO     | data_utils.py:80 | skipped: 0, total: 4
Using noise scaled MAS for VITS2
Using duration discriminator for VITS2
INFO:models:Loaded checkpoint 'Data/WangMingJun\models\DUR_0.pth' (iteration 0)
ERROR:models:emb_g.weight is not in the checkpoint
INFO:models:Loaded checkpoint 'Data/WangMingJun\models\G_0.pth' (iteration 0)
PytorchStreamReader failed reading zip archive: failed finding central directory
  0%|                                                                                            | 0/6 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "train_ms.py", line 852, in <module>
    run()
  File "train_ms.py", line 387, in run
    train_and_evaluate(
  File "train_ms.py", line 613, in train_and_evaluate
    loss_gen_all += loss_dur_gen + loss_lm + loss_lm_gen
UnboundLocalError: local variable 'loss_lm' referenced before assignment

**Comment by v3ucn** [comment]
不一样，Bert-VITS2_中文特化底模和Bert-VITS2_中文特化修复底模不是一个东西，如果是用fix底模，你就得去克隆fix分支的代码
